name: propresenter_api
description: An implementation of the ProPresenter API (legacy and current) for Dart.
version: 0.3.0
homepage: https://www.jeffmikels.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  # ProPresenter's API runs over standard http methods and websockets
  http: ^0.13.4

  # ProPresenter sometimes sends TIFF images. To make things easier
  # on Flutter developers, we use the `image` library to transcode
  # images to jpg
  image: ^3.1.3
  
  # ProPresenter instances advertise themselves with multicast
  multicast_dns: ^0.3.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
